### ISSUE TITLE
Expansion_Tefnut has duplicate folder of itself

### ISSUE THREAD

**Issue by CV514** [Kenan2000/Bright-Nights-Kenan-Mod-Pack#13]
It's in `/Expansion_Tefnut/expansion_tefnut/`
Which produces

`src/mod_manager.cpp:216 [void mod_manager::load_modfile(const JsonObject&, const string&)] there is already a mod with ident expansion_tefnut`

Seems like folder inside of folder has more recent changes, should be double-checked just in case of what to remove.

**Comment by Kenan2000** [comment]
I believe that this fixes it https://github.com/Kenan2000/Bright-Nights-Kenan-Mod-Pack/commit/68bca0d176c4876c34b981b061c2570a85b7b7af , thank you for noticing this error, @CV514 , truly appreciate it :-)
