### ISSUE TITLE
JSON duplicate comment keys rework

### ISSUE THREAD

**Issue by CV514** [Kenan2000/Bright-Nights-Kenan-Mod-Pack#16]
According to https://github.com/CleverRaven/Cataclysm-DDA/blob/master/doc/JSON_INFO.md

If we want multiple comments in a single object then append a number to //. For example:

```
{
  "//" : "comment",
  "//1" : "another comment",
  "//2" : "yet another comment"
}
```

And since https://github.com/CleverRaven/Cataclysm-DDA/pull/40390 (BN: https://github.com/cataclysmbnteam/Cataclysm-BN/pull/324)

We're in the works of fixin'! Yay

For examle, Secronom:

```
Error: data/mods//secronom/Modification Files/Items/secro_guns.json: line 266:14: duplicate entry in json object

        "volume": "2500 ml",
        "price": 2144000,
        "//":
             ^
              "Didn't see a price for this.",
        "to_hit": -1,
        "bashing": 12,
```

I'm opening this up as a milestone issue.

**Comment by Kenan2000** [comment]
This has been fixed a while ago too
