### ISSUE TITLE
Lesser mana potions (Magiclysm mod) stocked in grocery stores

### ISSUE THREAD

**Issue by Proxiehunter** [Kenan2000/Bright-Nights-Kenan-Mod-Pack#18]
Is this intended behavior? Not sure those are supposed to be something pre-cataclysm folks could just pop down to Walmart for.

**Comment by Kenan2000** [comment]
@Proxiehunter Yes, this is intended, I'm not the creator of the mod, I'm just a maintainer of it, never touched the item groups or the spawns in first place, the lines that you are mentioning in the JSON item groups file are these, you won't mind if I close the issue now? :-) ```{
    "type": "item_group",
    "id": "displays",
    "items": [
      [ "mana_potion_lesser", 50 ],
      [ "magi_staff_minor", 5 ],
      [ "wizard_hat", 5 ],
      [ "cauldron_demon_chitin", 3 ],
      [ "manatouched_serum", 3 ],
      [ "wolfsbane", 2 ]
    ]
  }, 
  {
    "id": "coffee_display_2",
    "type": "item_group",
    "items": [ [ "mana_potion_lesser", 10 ] ]
  },
  {
    "type": "item_group",
    "id": "bar_alcohol",
    "items": [ [ "mana_potion_lesser", 20 ], [ "manatouched_serum", 1 ] ]
  },
  {
    "type": "item_group",
    "id": "bar_fridge",
    "items": [ [ "mana_potion_lesser", 5 ] ]
  },
  {
    "type": "item_group",
    "id": "pizza_soda",
    "items": [ [ "mana_potion_lesser", 3 ] ]
  },
{
    "type": "item_group",
    "id": "pizza_beer",
    "items": [ [ "mana_potion_lesser", 5 ] ]
  },
  {
    "id": "groce_softdrink",
    "type": "item_group",
    "items": [ [ "mana_potion_lesser", 15 ] ]
  },```
