### ISSUE TITLE
Early-Game Mutations mod scenario doesn't work

### ISSUE THREAD

**Issue by c67f** [Kenan2000/Bright-Nights-Kenan-Mod-Pack#19]
Using either of the scenarios from the Early-Game Mutations mod doesn't work. It says "unable to generate a valid starting location BMC first floor [cs_bod_mod_clinic_z1 in a radius of 3 overmaps." (ground floor also does the same thing). I've tried it on a world with largely default world generation settings (I think the only things different are monster resilience and speed, and item generation) and it still does this.

**Comment by Kenan2000** [comment]
@c67f I've fixed it in the latest update, check it out and see if it works now :-)

**Comment by c67f** [comment]
It mostly works, although I picked "bmc first floor" and it spawned me on the roof of the building next to the bmc, instead of actually in the bmc.
