### ISSUE TITLE
Overrun scenario not working

### ISSUE THREAD

**Issue by c67f** [Kenan2000/Bright-Nights-Kenan-Mod-Pack#20]
I just had the same issue as I had before, but with the Overrun scenario (no such building found within 3 overmaps).

**Comment by Kenan2000** [comment]
@c67f I've searched for overrun scenario in the mod files of the Modpack and cannot finding any building or location alterations or changes, should we close this issue or you might as well find some clues to help out solving this?

**Comment by c67f** [comment]
Huh-testing it a little more, it looks like worked when I picked Lab technician as the profession, but not when I pick Bionic Sniper. Not sure about the other professions.

**Comment by Kenan2000** [comment]
No idea how to fix this currently, we'll need a bit more details, it seems
