### ISSUE TITLE
Имена модов приведи к общему знаменателю.

### ISSUE THREAD

**Issue by SomeDeadGuy** [Kenan2000/Bright-Nights-Kenan-Mod-Pack#21]
CDDA моды у тебя в одной папке лежат, а в BN в другой.
Пример
Дда Vermilion_Mod
Бн VermilionMod-master

Мне в тайлсете папки с модовыми тайлсетами приходится дублировать из-за этого.

**Comment by Kenan2000** [comment]
> CDDA моды у тебя в одной папке лежат, а в BN в другой.
> Пример
> Дда Vermilion_Mod
> Бн VermilionMod-master
> 
> Мне в тайлсете папки с модовыми тайлсетами приходится дублировать из-за этого.

В новейших обновлениях все исправлено и теперь используется один общий формат названия для папок, еще добавил твои тайлы к некоторым модам во всех Модпаках, которых там раньше не было. Еще проверь, пожалуйста, удали старые названия папок, замени их новейшими

**Comment by SomeDeadGuy** [comment]
Косяки остались ещё.
![image](https://user-images.githubusercontent.com/37592026/111864483-35fd4580-8972-11eb-96d7-1fd16ff02db6.png)
![image](https://user-images.githubusercontent.com/37592026/111864490-3dbcea00-8972-11eb-8195-eef24c93bfc6.png)
![image](https://user-images.githubusercontent.com/37592026/111864504-4d3c3300-8972-11eb-92f1-96e386470c5b.png)
![image](https://user-images.githubusercontent.com/37592026/111864518-6349f380-8972-11eb-9e30-b5836405c184.png)
![image](https://user-images.githubusercontent.com/37592026/111864552-9f7d5400-8972-11eb-89c3-458b51aed651.png)
![image](https://user-images.githubusercontent.com/37592026/111864557-a60bcb80-8972-11eb-9284-03a1321551d2.png)
![image](https://user-images.githubusercontent.com/37592026/111864561-ad32d980-8972-11eb-903f-7721d42f13e7.png)
![image](https://user-images.githubusercontent.com/37592026/111864573-d3587980-8972-11eb-900c-8d5be309a044.png)

**Comment by Kenan2000** [comment]
> Косяки остались ещё.
> ![image](https://user-images.githubusercontent.com/37592026/111864483-35fd4580-8972-11eb-96d7-1fd16ff02db6.png)
> ![image](https://user-images.githubusercontent.com/37592026/111864490-3dbcea00-8972-11eb-8195-eef24c93bfc6.png)
> ![image](https://user-images.githubusercontent.com/37592026/111864504-4d3c3300-8972-11eb-92f1-96e386470c5b.png)
> ![image](https://user-images.githubusercontent.com/37592026/111864518-6349f380-8972-11eb-9e30-b5836405c184.png)
> ![image](https://user-images.githubusercontent.com/37592026/111864552-9f7d5400-8972-11eb-89c3-458b51aed651.png)
> ![image](https://user-images.githubusercontent.com/37592026/111864557-a60bcb80-8972-11eb-9284-03a1321551d2.png)
> ![image](https://user-images.githubusercontent.com/37592026/111864561-ad32d980-8972-11eb-903f-7721d42f13e7.png)
> ![image](https://user-images.githubusercontent.com/37592026/111864573-d3587980-8972-11eb-900c-8d5be309a044.png)
> ![image](https://user-images.githubusercontent.com/37592026/111864592-f8e58300-8972-11eb-9f54-b36688e812d4.png)

Исправлено, во всех Модпаках один и тот же формат названия папок, теперь можешь вытащить меня из блока в дискорде, пожалуйста?

**Comment by SomeDeadGuy** [comment]
Окей.

**Comment by SomeDeadGuy** [comment]
Ещё нашёл
WHALEYS_TALL_BUILDINGS
WHALEYS TALL BUILDINGS

ты забыл
Wild_Living
WildLiving

**Comment by Kenan2000** [comment]
Теперь и это поправлено тоже
