### ISSUE TITLE
Pneumatic fun: Alloy-coated pebble recipe

### ISSUE THREAD

**Issue by Unrepentant-Atheist** [Kenan2000/Bright-Nights-Kenan-Mod-Pack#22]
The alloy-coated pebble from pneumatic fun, pebble_mk4, has only 40 pebbles, to make 40 alloy coated pebbles. Bit OP for mk4 pebbles that decimate everything.

https://i.imgur.com/9Ied9Sx.png

**Comment by Kenan2000** [comment]
Updated and properly balanced for both Modpacks in the latest update :-)
