### ISSUE TITLE
Trading values of mod items

### ISSUE THREAD

**Issue by Unrepentant-Atheist** [Kenan2000/Bright-Nights-Kenan-Mod-Pack#24]
Some mods have unrealisticly high trading values of items: Like wicker shield from More_Makeshift_Stuff or Wooden Shield, easy to craft, high value. Makes trading...pointless.

**Comment by Kenan2000** [comment]
@Unrepentant-Atheist I'm not the original creator of these mods, I'm not too savvy in terms of balancing the content that I'm only maintaining to work in a stable manner on latest release versions, could you suggest the updated values of these items and maybe change them and publish a pull request?

**Comment by Unrepentant-Atheist** [comment]
Can do, gotta think what appropriate values are.

**Comment by Kenan2000** [comment]
Will close this for now until you PR me the updated values which you find balanced to some extent
