### ISSUE TITLE
Secronom and BL9 dependency errors

### ISSUE THREAD

**Issue by CV514** [Kenan2000/Bright-Nights-Kenan-Mod-Pack#33]
After recent update https://github.com/Kenan2000/Bright-Nights-Kenan-Mod-Pack/commit/6bf8e8a1ccf484d252dda0d78abf26f710efb02d there are several errors that should be looked into.

`<14:02:33.320 ERROR : src/generic_factory.h:457 [int_id<T> generic_factory<T>::convert(const string_id<T>&, const int_id<T>&) const [with T = furn_t]] invalid furniture id "f_console">`
Caused by: `f_console` being defined in BL9 files and used in Secronom maps.

```
src/main_menu.cpp:1153 [bool main_menu::load_character_tab(bool)] Error: line 57:19: unknown npc class

        { "class": "secronom_scientist", "x": 13, "y": 10 },
        { "class": "secronom_researcher", "x": 16, "y": 14 },
        { "class":
                  ^
                   "secronom_guard", "x": 10, "y": 17 }
      ],
      "monster": { "a": { "group": "GROUP_SECROLAB_ALL", "chance": 60 } },
```
Caused by: `secronom_guard` being used in `SecronomBunker.json` of Secronom mod, but NPC class is defined in Secronom Lore Expansion `secro_npcs.json`

For now this can be fixed by correct manual mod order:
BL9
Secronom
Secronom+ Lore Expansion

Suggestion: merging Secronom mods, and either define their separate `f_console`, or create an dependency on BL9 so it's automatically loads after it and require it in the word mod list, if that's in line of those mods ongoing development.

**Comment by Kenan2000** [comment]
@CV514 Nice, thank you for this, fixed this in the latest update here both for 0_E3 Modpack version and Bright Nights Modpack as well https://github.com/Kenan2000/Bright-Nights-Kenan-Mod-Pack/commit/67732f017d702ca6f95bd528301c095b59e124f5, here
