### ISSUE TITLE
PKs Rebalancing .410 ammo issues

### ISSUE THREAD

**Issue by CV514** [Kenan2000/Bright-Nights-Kenan-Mod-Pack#35]
There are no recipes for .410 shots, you can't craft or disassembly them despite they are simpler version of regular 12 gauge stuff.
But more than that, all of the .410 ammo in this mod defines it's own .410 empty casing there is already defined ammo of that type in the base game, `410shot.json`

Mod files are defining more types of that caliber, so before adding recipes mentioned above it would be wise to check consistency of stats with the base game.

**Comment by Kenan2000** [comment]
Will you be able to work on this addition yourself when you have some time?Currently, I'm juggling all kinds of stuff in terms of other mods, some updates and content additions that I'd like not to reveal right now so working on polishing or adding content to other existing mods in the Modpacks is not really in my priorities with regards to mods right now, hopefully, you can understand me in this case :-)

**Comment by CV514** [comment]
Sure thing! I'll leave that open to not forget things I've just mentioned.

By the way, PR of mine is in semi-finished state for now and can be merged, if you please.

**Comment by CV514** [comment]
Closed as of https://github.com/Kenan2000/Bright-Nights-Kenan-Mod-Pack/pull/34 merge
Thanks! (and sorry for my formatting mess)
