### ISSUE TITLE
Secronom Reverting Intake Changes - Cattle/Other Creatures Not Remaining Tamed

### ISSUE THREAD

**Issue by DrPariah** [Kenan2000/Bright-Nights-Kenan-Mod-Pack#46]
ISSUE: Cattle in the base game (and mod added creatures that take Cattle Fodder to tame) normally take one Cattle Fodder to tame. You can thereafter interact with the tamed animal at will (Play with it, armor it, milk a cow, etc.). Something in Secronom is causing this to break. Cows are a good 'core' example, as they are not remaining tamed once the initial Cattle Fodder has been applied.

NOTE: This seems to revert fix under [https://github.com/cataclysmbnteam/Cataclysm-BN/issues/174](url)

STEPS TO REPRODUCE:
1) Create a new world, vanilla.
2) Debug spawn at least 2 Cattle Fodder and a Cow.
3) Tame Cow with Cattle Fodder.
4) Interact with Cow, then take one step away and attempt to interact again. This should bring up the interaction menu both times.
5) Create a new world using Secronom from the BN Mod Pack.
6) Repeat Steps 2 & 3 above
7) Interact with Cow, then take a step away and attempt to interact again - this should result in the action simply (E)xamining the square the now-friendly Cow is in.
8) Use another Cattle Fodder on Cow, interaction menu available again.
9) If you repeat the step away and attempt to interact process, you should get the same result as above.

VERSIONS:
BN Version a40a4de (haven't updated to current release yet)
BN Modpack version release on 6/19/21 (also need to update to current version)

**Comment by Kenan2000** [comment]
Well, this is weird, are you sure that you're spawning a mon_cow, not mon_sflesh_cow which shares same name as mon_cow aka a regular cow yet their ids are different, these are two separate monsters? This is honestly weird because Secronom is not in any of it's JSON files altering existing vanilla monsters or mammals including cows, it has spells which technically kill regular cow, summoning a flesh-infested one, it does not alter core cows definitions as well, technical solution that is remotely close to fixing this is adding EATS_CROP as a special attack to Secronom mammals including cows cause they lack them currently, maybe this is what causes this, not sure

**Comment by DrPariah** [comment]
100% positive. Flesh Cows are bright red, and they have an ID in the Debug menu of something like 497 or so. I've been spawning regular Cows to test. Also, if you load up Dinomod and spawn a Triceratops (which can be tamed with Cattle Fodder) you get the same thing happening. It's weird, and I'm right there with you - I can't figure out why this mod, particularly, would cause it to break. I've tested the other mods, one by one and in sequence, that either modify existing critters (Tameable Bugs) or add new ones (Dinomod) that can be tamed, none of the others have any impact.

**Comment by DrPariah** [comment]
Tested adding "EATS_CROP" as special attack: did not work. Cows still won't stay tamed. 
Deleted Flesh Cow & Flesh Calf from record: did not work. Apparently the presence or absence of Flesh Cows doesn't impact regular cows.
I'm looking at the mod itself, and I'm not seeing anything that affects item placement, or fodder, or whatnot. I'm going to ask on the original intake referenced above as to how that fix worked, maybe that might tell us what the problem is.

**Comment by DrPariah** [comment]
Found it, now have to figure out how to fix it. The effect below overwrites the effect ID 'pet', which is normally permanent. I'm a bit confused as to how or why the option to tame a Secronom Dragon is there, simply because there's no route to tame it nor is it hackable. 

Bright-Nights-Kenan-Mod-Pack/Kenan-BrightNights-Modpack/secronom/Modification Files/Monsters/-Essentials/secro_effects.json

`  {
    "//": "Used only on tamed secronom dragon, so players would be able to ride it.",
    "type": "effect_type",
    "id": "pet",
    "max_duration": 10,
    "name": [ "Dragon" ],
    "desc": [ "tamed secronom dragon." ]
  },`

**Comment by DrPariah** [comment]
OK, pull submitted. Can close this one out. Yay, go team me!
