### ISSUE TITLE
Overheating causes you to starve to death

### ISSUE THREAD

**Issue by Valikdu** [Kenan2000/Bright-Nights-Kenan-Mod-Pack#49]
I'm not sure if this is an issue in vanilla BN, its default mods or in the modpack.

I've added an issue over there as well: https://github.com/cataclysmbnteam/Cataclysm-BN/issues/650

Basically, if you're under the effects of Very Hot! (hampered, warm, hot) your hunger meter will drop by hundrers of Kcal per step until you drop dead from starvation.

My full list of mods is: 

[
Dark Days Ahead [dda],
Disable NPC Needs [no_npc_food],
<color_light_blue>BL9-100%-monster-resilience-version [BL9_100monres],
<color_light_red>Secronom [secronom],
<color_light_red>Secronom+ Lore Expansion [secronom_lore_expansion],
Aftershock [aftershock],
Arcana and Magic Items [Arcana],
Battle Maid Redux [battle_maid],
C.R.I.T Expansion Mod [crt_expansion],
M.A.G. Armory Mod [M.A.G.Armory],
Magiclysm [magiclysm],
Make bows great again [bow_opness],
Nechronica Redux [Nechronica_Redux],
Pneumatic fun [pneumo_fun],
Mutant NPCs [mutant_npcs],
Psychiclysm [psychiclysm],
Whaleys Collectables [collectablemod],
XEAS [XEAS],
Adurnsyl's Assorted Arms and Armour [AAA],
Advanced Gear [adv_gear],
Advanced Technologies [advtech],
Alexs Mutant Power Armor [a_mutated_arsenal],
Animal Summoner Item [Summons_animals],
anti-fungal gear [anti_fungal_gears],
Armor Up! PA Utilities [ArmUpPAUtil],
Armor Up! Survivor Expansion [ArmUpSurvEx],
Arsenal Breach [arsenal_breach],
Bens GF recipes [Tolerate_This],
BioCo Content [bioco],
Bionic Space Expander [Bionic_Space_Expander],
Bionics Systems Recipes [bio_recipes],
Modular Turrets with No Blacklist [modular_turrets_no_blacklist],
Bootleg Walkers [Bootleg_Walkers],
Broken Admin's Makeshift Items [bsam],
Camping tools [camping_tools],
Cannalan Importers [Cannala],
CBM Equipment [CBM_Arms],
CIVILIAN POWER ARMOR [CIVILIANPOWAAA],
Craft Ammo Mags & Belt Links [SD_Magcrafting],
Craftable Gun Pack [craftgp],
Culinary Days Ahead [culinary_days_ahead],
DeadLeaves' Fictional Guns [FIC_Weapons],
Disinfectant Powder [powder_disinfectant],
Dried Fruits [dried_fruits],
Dual Wield .22s [dual_wield_22],
Medieval and Historic Classes and Shields [Medieval_Stuff],
Dumb Sabaton Memes Mod [Dumb Sabaton Memes Mod],
ETC Handguns etc [ETC_handguns_etc],
Expanded Archery [ExArch],
Flowerpot (uekibati) mod [Uekibati_mod],
Garden Pots [growable-pots],
Gourmand's Graces [Gourmand'sGraces],
Gun Cotton [guncotton],
Homemade Fungicide [homemade_fungicide],
Homestead Instruments Inc. [homestead],
Icecoon's Arsenal [ew_pack],
Incinerator [incinerator],
Large capacity storage CBMs [eps_cbm],
Magical Plants [materials_plants],
Make a Lot of Items [Make_a_Lot_of_Items_Mod],
Makeshift engine hoist [makeshift_engine_hoist_mod],
Makeshift Items Mod [makeshift],
MakeshiftCanteen [MSCanteen],
Medieval Mod Reborn [Medieval_Mod_Reborn],
Metal materials [metal_elemental],
Miscellaneous Magiclysm Expansions [demon_spider_a],
MOD to grow tea leaves [More tea leaf],
Modern Weapon Pack Expanded [modern_weapon],
More Armors [More_Armors],
More Makeshift Stuff [makeshift_stuff],
More Survivor Notes [more_survive_notes],
MST Extra [MST_Extra],
Mythological Replicas [nw_pack],
Nuclear .50 Mod [nuclear_ball],
Pipe Revolver Rifles [pipe_revolver_mod],
Pixel's Various Fuckery [Pix's Shit],
Pora's Complilation [porawep],
Portable Coolers [portable_cooler],
Power_Armor_Additions [Power_Armor_Additions],
Pressure Weapons [pressure_weapon],
Private Defense [private_defense],
Project APEX [apex],
Recovery of rotten stomach and offal [stomach_offal],
RF food keeper [rf_food_keeper],
Ricky's Future Armory [futurearmory],
Rivtech Beam Swords [beamswordmod],
Rubber Band Sheath [rubber_band_sheath],
Sane Weapon Pointy Bits [SWPB],
seuzpack [seuzpack],
Sewing Machine [SM],
Soy mod [Soy mod],
Space Heater [space_heater],
Survivor's Lost item [Survivors_Lost_item],
Survivor crowbar [surv_crowbar],
The Glory Of Cereal! [CerealMod],
Thermal Electric UPS [thermal_ups],
Wild Living [WildLiving],
Crazy Labs [crazy_labs],
DinoMod [DinoMod],
Draco's Pig Mod [DracoPigMod],
Cataclysm++ [Cata++],
Draco's Dog Mod [DracoDogMod],
Compatible Add Bandits [GOV_BANDITS],
Jury-Rigged Robots [jury_rigged_robots],
PKs Rebalancing [PK_REBALANCE],
Salvaged Robots [Salvaged_Robots],
Vampiric Stuff [vamp_stuff],
Mutant Animals [mutant_animals],
Mutant Insects [mutant_insects],
World on Fire [World_on_fire],
Youkai Enemies [Youkai_Disco],
Mythical Martial Arts [MMA],
<color_yellow>Mythical Martial Arts - Mods Extension [MMA_Mods_Extension],
Alternative Map Key [alt_map_key],
CDDA Variety Pack [ks_variety_pack],
Convenient Constructions [convenientconstructions],
Even More Mutations [even_more_mutations],
Food Irradiator [food_irradiator],
Hydroponics [hydroponics],
Locked Locker [locked_locker],
Mining Mod [Mining_Mod],
More Survivor Stuff [more_survivor_stuff],
Wandering Masters [wandering_masters],
Alternative Basement Layouts [basement_extension],
Dorf Life [Dorf_Life],
More Locations [more_locations],
Fuji's More Buildings [FujiStruct],
Morlock Village [morlock_village],
Oa's Early Game Mutations mod [oa_early_game_mutations_mod],
Randomized Mall [randomized_mall],
Trailer Parks [trailerpark],
Water Towers [water_towers],
Whaleys TALL Buildings [whaleys_tallbuild],
Cars to Wrecks [cars_to_wrecks],
Folding Parts pack [deoxymod],
Tankmod: Revived [Tankmod_Revived],
Roadheader and other mining vehicles [Heavy miners],
Shrub it off [shrub_mod],
Necromancy [necromancy],
Graphical Overmap [Graphical_Overmap],
sees-player icon, retrodays [sees_player_retro],
Abrahms Recipes 1 [AbrahmsRecipes1],
Artyoms' Gun Emporium - Reloaded [Arts' Guns],
Merchant Mod [Merchant],
Nimian Manufacture Guns [NM_wpns],
ProjectKawaii [ProjectKawaii],
Science Turret [sci_turret],
Targeted Mutations [TaMu]
]

**Comment by DrPariah** [comment]
I've noticed this as well. Stand next to a bonfire, get to Very Hot, try to step away, watch your caloric intake drop to negatives faster than a politician's approval rating.

**Comment by Valikdu** [comment]
I think it's the effect overrride in PK's Rebalance mod. It adds "hunger_max: [1]" to the hot effect. I removed it and the calory drop rate seems to have subsided

**Comment by chaosvolt** [comment]
There's no `hunger_tic` on the effect, I assume? If there isn't, then it'd be incrementing hunger by 1 every second. For reference, default hunger rate is 1 every 5 minutes. I assume this was a holdover from back when turns were 6 seconds but even then that'd be some wacky hunger gain.

It's also possible that the stomach mechanics in DDA maybe made the problems caused by that system less noticeable, whereas BN has a more streamlined version of the stomach mechanics, possibly causing stored calories to be better in sync with hunger.

**Comment by Valikdu** [comment]
Yeah, it's the only string about hunger.
