### ISSUE TITLE
Сircular dependency in nocts_cata_mod_BN

### ISSUE THREAD

**Issue by CV514** [Kenan2000/Bright-Nights-Kenan-Mod-Pack#5]
```
ERROR : src/init.cpp:142 [void DynamicDataLoader::load_deferred(DynamicDataLoader::deferred_json&)] JSON contains circular dependency.  Discarded 1 objects:
{
    "id": "stealth_cloak_f",
    "copy-from": "acs_74_stealth_cloak_off",
    "type": "TOOL_ARMOR",
    "name": "ACS-74 stealth cloak"
  },
```

https://github.com/Noctifer-de-Mortem/nocts_cata_mod/tree/master/nocts_cata_mod_BN

Loading BN and only Cataclysm++ in the mod list. Random character generation in newly created world. It abrupt chargen and returns to the main menu.

It seems like there should be no Legacy.json file at all; perhaps wrong mod package (for DDA, not BN)?
Removing folder from current mod pack and replacing it from BN version from the link above fixed it.

Also, for some reason it produces 

`src/item_action.cpp:221 [void item_action_generator::check_consistency() const] Item action "repair_myomer" isn't known to the game.  Check item action definitions in JSON.`

Which is seems like missing dependency on CBMArms mod; adding it to the mod list removes error pop up.

**Comment by Kenan2000** [comment]
@CV514 just uploaded the fix for Cata++ https://github.com/Kenan2000/Bright-Nights-Kenan-Mod-Pack/commit/4b9a610f459f744096ea45f441d5f281554e171e , tell me if it fixes this :-)

**Comment by CV514** [comment]
Nice, everything seems to be working fine, thank you.
