### ISSUE TITLE
Issues with Tolerate This! and Sewing Machine

### ISSUE THREAD

**Issue by Valikdu** [Kenan2000/Bright-Nights-Kenan-Mod-Pack#50]
Tolerate This!: it's supposed to add gluten-free food recipes for characters with an allergy, but, as it seems, it just duplicates food recipes and makes a mess out of your crafting menu. 
Proposition: Maybe it should just go.

Sewing Machine: is supposed to add variants of clothing recipes for use with a sewing machine, which would work faster, but there's no actual sewing machine. So, there's just a bunch of recipes that let you craft armor very fast for no reason, and they feel like cheating.
Proposition: Maybe it should also just go; however, as there are some interesting recipes contained here that have been "realism'd" from DDA and not returned to BN (bone armor), maybe there should be a replacement mod with recipes (not super fast ones) of bone armor? I can write it.

**Comment by DrPariah** [comment]
There is a sewing machine in the mod, it's not furniture but an item that spawns and has a sewing of 3. It really should be Sewing 4, illogical that a sewing machine should be less capable than a Tailor's Kit.
Setting aside 'cheating' arguments (its a single player game, just don't use the elements you don't want to), it'd make more sense to have a sewing machine be deployable furniture. Give it an extra quality, update the duplicate recipes to require that quality (so you need the sewing machine to use them), and it's a logical item that's still fun to use and gives a reward for setting it up.
As far as Tolerate This goes, I have no experience. I've literally never used it.
