### ISSUE TITLE
 Secronom generating error for monster group

### ISSUE THREAD

**Issue by DrPariah** [Kenan2000/Bright-Nights-Kenan-Mod-Pack#55]
DEBUG    : monster group GROUP_VEINSTALK_CRAWLER has unknown default monster mon_sflesh_veinstalk_crawly

 FUNCTION : static void MonsterGroupManager::check_group_definitions()
 FILE     : src/mongroup.cpp
 LINE     : 423
 VERSION  : BN 28b5d23

 Running both Secronom and the Lore Expansion mod for it. Appears to be an invalid monster ID for the crawly veinstalk, as this is one of two errors. Have tried deleting Secronom and reinstalling latest mod pack version, have not yet tried the separate Secronom repo version.

EDIT: Here's the other error.

DEBUG    : invalid monster type id "mon_sflesh_veinstalk_crawly"

 FUNCTION : const T& generic_factory<T>::obj(const string_id<T>&) const [with T = mtype]
 FILE     : src/generic_factory.h
 LINE     : 438
 VERSION  : BN 28b5d23

**Comment by Kenan2000** [comment]
@DrPariah Nice find, fixed this in latest updates :-)
