### ISSUE TITLE
Blazemod recipe errors & circular dependencies

### ISSUE THREAD

**Issue by qrrk** [Kenan2000/Bright-Nights-Kenan-Mod-Pack#57]
Please see my [debug.log](https://github.com/Kenan2000/Bright-Nights-Kenan-Mod-Pack/files/7267184/debug.log)

**Comment by Ignaramico** [comment]
<details>    
 DEBUG    : Recipe vehicle_shelving defines invalid result.

 FUNCTION : recipe_dictionary::finalize_internal(std::map<string_id<recipe>, recipe>&)::<lambda(const recipe&)>
 FILE     : src/recipe_dictionary.cpp
 LINE     : 371
 VERSION  : BN 94734f5

 DEBUG    : Recipe afs_metal_rig defines invalid result.

 FUNCTION : recipe_dictionary::finalize_internal(std::map<string_id<recipe>, recipe>&)::<lambda(const recipe&)>
 FILE     : src/recipe_dictionary.cpp
 LINE     : 371
 VERSION  : BN 94734f5

 DEBUG    : Recipe afs_kitchen_rig defines invalid result.

 FUNCTION : recipe_dictionary::finalize_internal(std::map<string_id<recipe>, recipe>&)::<lambda(const recipe&)>
 FILE     : src/recipe_dictionary.cpp
 LINE     : 371
 VERSION  : BN 94734f5

 DEBUG    : Recipe afs_cooking_rig defines invalid result.

 FUNCTION : recipe_dictionary::finalize_internal(std::map<string_id<recipe>, recipe>&)::<lambda(const recipe&)>
 FILE     : src/recipe_dictionary.cpp
 LINE     : 371
 VERSION  : BN 94734f5

 DEBUG    : vehicle part cargo_rack_extended uses undefined item vehicle_shelving

 FUNCTION : static void vpart_info::check()
 FILE     : src/veh_type.cpp
 LINE     : 612
 VERSION  : BN 94734f5



</details>
