### ISSUE TITLE
Missing item definition: taurus38mag in Modern Weapons Pack Expanded (and couple of other minor issues)

### ISSUE THREAD

**Issue by CV514** [Kenan2000/Bright-Nights-Kenan-Mod-Pack#6]
```
12:59:51.134 ERROR : src/item_factory.cpp:1361 [const itype* Item_factory::find_template(const itype_id&) const] Missing item definition: taurus38mag
12:59:57.205 ERROR : src/item_factory.cpp:1317 [void Item_factory::check_definitions() const] warnings for type automag:
magazine "taurus38mag" specified for "38" is not a magazine
```

I am confused but it seems like taurus38mag is just not in the game anymore, therefore AutoMag from that mod is sad and throwing some errors. 

I see two possible solutions: define that mag once again, or go with the flow and remove `[ "38", [ "taurus38mag" ] ]`  and .38 ammo compatibility for AutoMag completely in `modern_handgun.json`.
I've tried to bandage problem completely by replace mag with `[ "38", [ "38_speedloader5" ] ]` since in terms of ammo capacity and caliber it looks like same thing, but then I've received what seems to be simple error:

```
ERROR : src/item_factory.cpp:1317 [void Item_factory::check_definitions() const] warnings for type automag:
speedloader 38_speedloader5 capacity (5) does not match gun capacity (0).
```

But I'm not so sure how to work with it since other defined magazines for that gun have their own capacities, but not throwing any errors of that kind (still learning how everything works in this game, would PR otherwise, sorry).

**Comment by Kenan2000** [comment]
@CV514 Hello there, I've just uploaded another big fix/tweak update that hopefully resolves the Modern Weapon Pack Expanded error that you're experiencing - I've removed the taurus magazine and renamed some 357_mag to 357mag so that it would actually correspond to the existing vanilla ammo_type, it contains lots of other misc tweaks and fixes as well, cheers :-) https://github.com/Kenan2000/Bright-Nights-Kenan-Mod-Pack/commit/b0cb0119e92c6c76cb840692cce61456d86fa44f

**Comment by CV514** [comment]
Yep, should be it! Thank you for the tweaks 👍 

But with removal of magazine with .38 caliber you should remove ammo type ".38" in ammo array at line 77 in `modern_handgun.json`, otherwise it produces this error:

```
 ERROR : src/item_factory.cpp:1316 [void Item_factory::check_definitions() const] warnings for type automag:
specified magazine but none provided for ammo type 38
```

And I've mashed in some other mods from this modpack (I'm using like 90% of them atm), so I'll rename this Issue to represent them as well.

***

Issue after installing `cataclysmbn-1102-win64-tiles.zip` and b0cb0119e92c6c76cb840692cce61456d86fa44f 

```
 ERROR : src/emit.cpp:75 [static void emit::check_consistency()] emission intensity of emit_dazzle_bomblet out of range (2 of max 1)
 ERROR : src/emit.cpp:75 [static void emit::check_consistency()] emission intensity of emit_fvent_vile out of range (2 of max 1)
```
Seems to be PK_Rebalancing related, inside of `pk_emit.json`

and another one

```
 ERROR : src/item_group.cpp:127 [virtual void Single_item_creator::check_consistency(const string&) const] item id offering_chalice_used is unknown (in item in rare)
 ERROR : src/item_group.cpp:127 [virtual void Single_item_creator::check_consistency(const string&) const] item id offering_chalice_used is unknown (in item in cop_evidence)
 ERROR : src/item_group.cpp:127 [virtual void Single_item_creator::check_consistency(const string&) const] item id offering_chalice_used is unknown (in item in magic_tools)
```

That one feels like the mag situation above, trying to find offering_chalice_used while there is no such thing anywhere (since I'm blind about those mods and just analyzing debug log file, I'm searching text as "contents of file" for entire DDA folder to see the world, so to say). Chalice itself seems to be the part of Arcana_BN mod, and it's called from Ascension_Winning_DDA inside `item_groups.json`. I'm not completely sure what's the purpose of that thing, but replacing `offering_chalice_used` with `offering_chalice` removes error messages.

**Comment by CV514** [comment]
Closing since latest necessary change is in PR https://github.com/Kenan2000/Bright-Nights-Kenan-Mod-Pack/pull/8
