### ISSUE TITLE
Missing uncraft check for turret(s) in Modular Turrets mod

### ISSUE THREAD

**Issue by CV514** [Kenan2000/Bright-Nights-Kenan-Mod-Pack#7]
It seems like it's missing necessary section for disassemble .50 turrets, but at the same time it has one?

`uncraft_corpse.json` has the following
```
  {
    "result": "broken_milturret_50bmg",
    "type": "uncraft",
    "skill_used": "electronics",
    "difficulty": 2,
    "time": "3 m",
    "qualities": [ { "id": "SCREW", "level": 1 } ],
    "components": [ [ [ "broken_milturret_disarmed", 1 ] ], [ [ "robopart_50bmg", 1 ] ] ]
  },
```

But some turrets that are destroyed left behind not `broken_milturret_50bmg`, but `broken_turret_bmg`, which is virtually the same thing and I don't get it. Perhaps this should be looked into and there may be other turrets with that kind of behavior, or it may be just one; in that case, simply adding next code into uncraft json somewhere should be enough:

```
  {
    "result": "broken_turret_bmg",
    "type": "uncraft",
    "skill_used": "electronics",
    "difficulty": 2,
    "time": "3 m",
    "qualities": [ { "id": "SCREW", "level": 1 } ],
    "components": [ [ [ "broken_milturret_disarmed", 1 ] ], [ [ "robopart_50bmg", 1 ] ] ]
  },  
```

**Comment by Kenan2000** [comment]
@CV514 Thanks for these, just published these 2 commits thanks to your great assistance, indeed, you are right - some of the parts were missing uncraft recipes but now thanks to some extensive Notepad++'s search and comparison, all the parts have their respective recipes now, nothing is missing, all of this thanks to your awesome help :-) https://github.com/Kenan2000/Bright-Nights-Kenan-Mod-Pack/commit/eb8593967f935028dc6c123cee90d58d0c85c6e4, https://github.com/Kenan2000/CDDA-Kenan-Modpack/commit/6f07834e0215f73fda4eb56835b7739b9adbc1ae,

Check these out, has the issue been fully resolved at this point or there's anything else to fix?

**Comment by CV514** [comment]
Everything seems to be working fine so far, thank you.
Although I'll remind you to also add those changes into CDDA-BN modpack since I'm exclusively play with that one and posting stuff about it, not CDDA one. In this case it seems like there is no major difference between mods, so it's fine.

Also an little suggestion, adding a little more info about difference between `modular_turrets` and `modular_turrets_no_blacklist` in their respective `modinfo.json` would be great, or get rid of one of them altogether if this difference is not that important.

**Comment by Kenan2000** [comment]
> Everything seems to be working fine so far, thank you.
> Although I'll remind you to also add those changes into CDDA-BN modpack since I'm exclusively play with that one and posting stuff about it, not CDDA one. In this case it seems like there is no major difference between mods, so it's fine.
> 
> Also an little suggestion, adding a little more info about difference between `modular_turrets` and `modular_turrets_no_blacklist` in their respective `modinfo.json` would be great, ~or get rid of one of them altogether if this difference is not that important.~ disregard last one, modular_turrets is bundled with CDDA-BN itself; still would be great to add the actual difference in mod description.

@CV514 Oh I'm an idiot, my bad, I've sent you the wrong commit - https://github.com/Kenan2000/Bright-Nights-Kenan-Mod-Pack/commit/eb8593967f935028dc6c123cee90d58d0c85c6e4 , this one is for Bright Nights :-) 

By the way, thank you for all the work that you're doing and supporting me, I would like you to join our Cataclysm Modding Community server, I am most active there as well as other modders and players :-) https://discord.gg/7GAXrQH

**Comment by CV514** [comment]
I've found it later in commits, no problem! 
I'll hop in into server, but a few weeks later - for now I'm in working position that's not suitable for regular online presence (that's why I'm sticking with Cataclysm too)
